### ISSUE TITLE
convert() fails with unclear error message when extra_args is a string instead of a list

### ISSUE THREAD

**Issue by n-st** [JessicaTegner/pypandoc#197]
The README gives an example on how to use the `extra_args` argument:
```
output = pypandoc.convert('# Primary Heading', 'html', format='md', extra_args=['--base-header-level=2'])
```

One might, uhm, possibly, fail to notice that `extra_args` is given as a list.

When the same function is invoked with `extra_args` as a single string, it fails and produces a rather uninformative error message:
```
>>> output = pypandoc.convert('# Primary Heading', 'html', format='md', extra_args='--base-header-level=2')
[…]
RuntimeError: Pandoc died with exitcode "1" during conversion: b'pandoc: <stdin>: hGetBuf: illegal operation (handle is closed)\n'
```

Would it be possible to catch the type mismatch early and raise a more informative error (e.g. a TypeError, perhaps with a dedicated error message)? Or even add an automatic type conversion to support both strings and lists there?

**Comment by JessicaTegner** [comment]
Continuing discussion in #306
