### ISSUE TITLE
Platform architecture of ARM Linux system can be aarch64

### ISSUE THREAD

**Issue by adityaQure** [JessicaTegner/pypandoc#293]
https://github.com/JessicaTegner/pypandoc/blob/4becb4e6734036e7eee92d180ea8e7acc7333e6f/pypandoc/pandoc_download.py#L52

```
$ python
>>> import platform
>>> platform.architecture()
('64bit', '')
>>> platform.uname()
uname_result(system='Linux', node='6407f0ca881a', release='5.4.0-1066-aws', version='#69~18.04.1-Ubuntu SMP Wed Feb 9 15:39:21 UTC 2022', machine='aarch64')
>>> platform.uname()[4]
'aarch64'
```

ARM 64 linux is also available here: https://github.com/jgm/pandoc/releases

It's a small change and will be willing to send a PR. Thanks in advance.

**Comment by JessicaTegner** [comment]
@adityaQure  I would love a pr fixing this. Feel free to work on it :)

**Comment by hey24sheep** [comment]
@JessicaTegner Hi, I want to contribute to this. I have created a pull request as well to save your time.

**Comment by hey24sheep** [comment]
Hi, can you assign this to me and check my PR. The other PR didn't count towards my hacktoberfest contribution.

**Comment by JessicaTegner** [comment]
@hey24sheep  after doing some investigation, I figured out why.
I turns out that hacktoberfest only counts prs made after the 1st.

You are more than welcome to open more prs, as they should be counted from now on out :)

**Comment by hey24sheep** [comment]
@JessicaTegner :/ sad. So, can I close my PR and re-create it?

**Comment by JessicaTegner** [comment]
@hey24sheep  INDEED YOU CAN :)
