### ISSUE TITLE
pandoc version compatibility - suggested version for EPEL8

### ISSUE THREAD

**Issue by opoplawski** [JessicaTegner/pypandoc#318]
We're looking to package pypandoc for EPEL8 - see https://bugzilla.redhat.com/show_bug.cgi?id=1830821 
EPEL8 has pandoc 2.0.6.  pypandoc 1.6.4 builds fine and the tests succeed.  However 1.7.4 fails with:
```

FAIL: test_conversion_error (__main__.TestPypandoc)
----------------------------------------------------------------------
RuntimeError: Pandoc died with exitcode "2" during conversion: Unknown option --blah.
Try pandoc --help for more information.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tests.py", line 367, in test_conversion_error
    f()
AssertionError: "Pandoc died with exitcode "6" during conversion: Unknown option --blah" does not match "Pandoc died with exitcode "2" during conversion: Unknown option --blah.
Try pandoc --help for more information.
"
```
Not sure how serious this is or if it indicates we might see other incompatibilities with the version of pandoc in EL8.  Can you shed some like and make a suggestion for an appropriate version of pypandoc for EPEL8?  Thanks.

**Comment by JessicaTegner** [comment]
Hmm... Interesting. Can you confirm that pypandoc > 1.7x uses the correct version pf pandoc. Also I hope you aren't actually trying to use an argument called "--blah". But in anycase, it looks like, that the argument doesn't exist
