### ISSUE TITLE
Add a debug parameter

### ISSUE THREAD

**Issue by JessicaTegner** [JessicaTegner/pypandoc#320]
It could be useful to have a debug parameter to add more logging such as which files was found in the glob patterns in the convert* functions, what the command we are passing to pandoc look like and so on.

What do people think.

**Comment by saumcor** [comment]
Along with that can we disable setting the log level for the `root` logger by default here?
https://github.com/JessicaTegner/pypandoc/blob/master/pypandoc/handler.py#L15

**Comment by JessicaTegner** [comment]
@saumcor  indeed. We should make a pypandoc sublogger
