### ISSUE TITLE
Need to use glob.escape when convert file with name like '[0].txt'

### ISSUE THREAD

**Issue by shutaozhenzhen** [JessicaTegner/pypandoc#336]
Have problem in using pypandoc with path like '[0].txt', baceuse glob.glob returns `[]` and cause `format = _identify_format_from_path(discovered_source_files[0], format)` index out of range

Seems need to use glob.escape, which returns `['[[]0].txt']`.

**Comment by JessicaTegner** [comment]
Don't exactly know what you are asking for here, so I'm going to close this for now.
