### ISSUE TITLE
source verification runs before cworkdir

### ISSUE THREAD

**Issue by Lrakotoson** [JessicaTegner/pypandoc#342]
Hi 👋  

In the `convert_file(...)` function, the `cworkdir` is only aknowledged in `_convert_input(...)` function, which is called after the source verification at `_identify_path(source_file)`.

It would be more practical to check the files once the working directory has been defined.  
Otherwise, it would be necessary either to always give a path relative to the old working directory, or to give lists of absolute paths. Which is not really optimal when using extra_args.

**Comment by JessicaTegner** [comment]
ahh I see.
Nice catch.
Will look into this soon, if someone hasn't already.

It's at the top of the priority list
