### ISSUE TITLE
BUG🐞: Markdown to Word formatting issue

### ISSUE THREAD

**Issue by HlexNC** [JessicaTegner/pypandoc#343]
There is an unusual issue with formatting of markdown to docx, which doesn't seem to happen with other file formats. the `/n` is ignored and some characters are removed.

![CLI](https://github.com/JessicaTegner/pypandoc/assets/66517969/e5d32e07-631c-4db4-a164-d07facd1efd5)
![Output File](https://github.com/JessicaTegner/pypandoc/assets/66517969/ffef53d9-ae74-4a32-8aa4-b234f563d846)

---

![Source Code](https://github.com/JessicaTegner/pypandoc/assets/66517969/c171ef15-4d8e-4336-985a-e5bc5d907b0e)

**Comment by JessicaTegner** [comment]
hi @HlexNC  can you confirm the following:

* Version of pandoc and pypandoc being used
* If the same behaviour happens when using convert_file instead of convert_text

**Comment by HlexNC** [comment]
@JessicaTegner, I apologize for any confusion. The issue originated from FastAPI's conversion of `\n` into `\\n` and `\t` into `\\t`, which pandoc couldn't recognize. I'm currently using the latest versions of pandoc and Pypandoc. Please know that no action is required on your part. I thank you for maintaining and improving the repository.
