### ISSUE TITLE
"--wrap=auto | preserve| none" doesn't make any difference (HTML to OPML)

### ISSUE THREAD

**Issue by akuma73** [JessicaTegner/pypandoc#353]
thank you for your great application.

I tried to convert my HTML to OPML.
I want --wrap=preserve. but, "auto" option is forcibly turned on.

**Comment by didmar** [comment]
Similar problem here, but for converting docx to markdown.
```python
from pathlib import Path
import pypandoc

filepath = "./file.docx"
with Path(filepath).open("rb") as f:
    content = f.read()

print(pypandoc.convert_text(
    content,
    "markdown",
    format="docx",
    extra_args=["-s",  "--wrap=none"]
))
```
The output will be wrapped, ignore the `--wrap=none` argument.

But it does work when I use the equivalent pandoc command in the command line:
```bash
pandoc file.docx -t markdown -s --wrap=none
```

I'm using pypandoc v1.13 and pandoc 3.1.12.3

**Comment by JessicaTegner** [comment]
@akuma73  I cannot reproduce this
