### ISSUE TITLE
Keep <mark> tag when converting Markdown to Docx

### ISSUE THREAD

**Issue by bloodteller123** [JessicaTegner/pypandoc#366]
I have a markdown file with some sentences highlighted by <mark></mark> tag. I wonder if it's possible to capture the highlighted text in the docx with some reference docx, or trivial ways without need to customize pypandoc (or pandoc eventually), which seems impossible for a single dev.
Thanks..

**Comment by JessicaTegner** [comment]
Hi @bloodteller123 

While skimming through the pandoc user guide, this does not currently seem to be possible (unless you count the star symbols as marked).
At least not for Word documents.
I suggest opening this as a pr, on the main pandoc repository
