### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\.'

### ISSUE THREAD

**Issue by jrom99** [JessicaTegner/pypandoc#370]
This line raises the following warning for python3.12:

```
pypandoc/pandoc_download.py:61: SyntaxWarning: invalid escape sequence '\.'
```

The line in question:

https://github.com/JessicaTegner/pypandoc/blob/23f6f0924a8194a1171850b4c3f09253ffd97d52/pypandoc/pandoc_download.py#L61

This could be solved by turning the second string into a raw string:

```python
 regex = re.compile(r"/jgm/pandoc/releases/download/.*(?:"+processor_architecture+r"|x86|mac).*\.(?:msi|deb|pkg)") 
```

or just using using a raw f-string:

```python
 regex = re.compile(fr"/jgm/pandoc/releases/download/.*(?:{processor_architecture}|x86|mac).*\.(?:msi|deb|pkg)") 
```

**Comment by JessicaTegner** [comment]
I'll be able to get to it in a little while, otherwise, someone is welcome to open a quick pr for it.
SIdenote: raw f strings seems cool, didn't know they were a thing, especially not a thing so far back, compatibility wise.
