### ISSUE TITLE
Add executablePath Parameter for Custom Pandoc Executable Location

### ISSUE THREAD

**Issue by kcodesgh** [JessicaTegner/pypandoc#373]
I would like to suggest adding a key called executablePath as shown below (or in a similar way you think is best):

```
pypandoc = pypandoc(executablePath='/cache/pandoc_file')
pypandoc.convert_text(html_content, output_format, format='html', outputfile=tmpfile.name)
```
This would be similar to how Puppeteer allows specifying the Chrome executable path. It would enable us to set our own path externally. This feature would be particularly useful for those of us compiling with Nuitka, where we need to manually specify the path to the executable when the files are unpacked.

**Comment by JessicaTegner** [comment]
Hi. This is already possible through the "PYPANDOC_PANDOC" env variable.
Is this not sufficient for your usecase?

**Comment by kcodesgh** [comment]
sorry, i just saw it recently, Thanks for the notice. I didnt know how to delete my post so i left it ,u can close it now
